version = 1

[install]
forge.pkg-path = "flox/forge"
ollama-cuda.pkg-path = "flox/ollama-cuda"
ollama-cuda.pkg-group = "cuda"
ollama-cuda.systems = ["x86_64-linux", "aarch64-linux"]

[vars]
FORGE_HISTORY_FILE = "$FLOX_ENV_CACHE/forge_history"
FORGE_HTTP_CONNECT_TIMEOUT = "30"
FORGE_HTTP_READ_TIMEOUT = "900"
FORGE_TOOL_TIMEOUT = "300"

[hook]
on-activate = '''
mkdir -p "$FLOX_ENV_CACHE"
cd "$FLOX_ENV_PROJECT"
'''

[include]
environments = [
    { remote = "flox/ollama" }
]

[options]
#systems = ["x86_64-linux", "aarch64-darwin"]
